#############################################################################
# Makefile for building: openTranslate
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  openTranslate.pro
# Template: app
# Command: D:\Qt\Qt5.4.0\5.4\mingw491_32\bin\qmake.exe -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile openTranslate.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = D:\Qt\Qt5.4.0\5.4\mingw491_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: openTranslate.pro D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/win32-g++/qmake.conf D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/spec_pre.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/qdevice.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/device_config.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/common/shell-win32.conf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/qconfig.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axbase.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axserver.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_clucene_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_core.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_core_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_declarative.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_declarative_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_designer.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_enginio.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_enginio_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_gui.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_help.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_help_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_location.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_location_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_network.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_network_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_nfc.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_opengl.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_positioning.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qml.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quick.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_script.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_script_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_sensors.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_sensors_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_serialport.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_sql.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_svg.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_testlib.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_uitools.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webkit.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webkit_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_websockets.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webview.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webview_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_widgets.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_winextras.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_winextras_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_xml.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/qt_functions.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/qt_config.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/qt_config.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/win32-g++/qmake.conf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/spec_post.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/exclusive_builds.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/default_pre.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/default_pre.prf \
		deployment.pri \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/resolve_config.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/exclusive_builds_post.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/default_post.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/qml_debug.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/declarative_debug.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/rtti.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/precompile_header.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/warn_on.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/qt.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/resources.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/moc.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/opengl.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/uic.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/windows.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/testcase_targets.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/exceptions.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/yacc.prf \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/lex.prf \
		openTranslate.pro \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/qtmaind.prl \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Cored.prl \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Quick.prl \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Widgets.prl \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Gui.prl \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Qml.prl \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Network.prl \
		D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile openTranslate.pro
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\spec_pre.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\qdevice.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\device_config.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\common\shell-win32.conf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\qconfig.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_clucene_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_core.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_help.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_location.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_location_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_network.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_script.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_script_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webview.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webview_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\qt_functions.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\qt_config.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\qt_config.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\win32-g++\qmake.conf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\spec_post.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\exclusive_builds.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\default_pre.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\default_pre.prf:
deployment.pri:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\resolve_config.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\default_post.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\qml_debug.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\declarative_debug.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\rtti.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\precompile_header.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\warn_on.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\qt.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\resources.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\moc.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\opengl.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\uic.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\windows.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\testcase_targets.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\exceptions.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\yacc.prf:
D:\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\lex.prf:
openTranslate.pro:
D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/qtmaind.prl:
D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Cored.prl:
D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Quick.prl:
D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Widgets.prl:
D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Gui.prl:
D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Qml.prl:
D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Network.prl:
D:/Qt/Qt5.4.0/5.4/mingw491_32/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile openTranslate.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		main.qml \
		base/TextEditArea.qml \
		base/DisplayArea.qml \
		base/InputArea.qml
	/home/stephen/Qt5.3.1/5.3/gcc/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_translate.cpp moc_baiduapidictresult.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_translate.cpp moc_baiduapidictresult.cpp
moc_translate.cpp: ../../Qt5.3.1/5.3/gcc/include/QtCore/QObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QtNetwork \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QtNetworkDepends \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QtCore \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QtCoreDepends \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qparallelanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpauseanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpropertyanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvariantanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeasingcurve.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsequentialanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextcodec.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qendian.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlibraryinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdatetime.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbuffer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdir.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfileinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdiriterator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfileselector.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QStringList \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfilesystemwatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlockfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qloggingcategory.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qprocess.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qresource.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsavefile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsettings.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstandardpaths.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtemporarydir.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QScopedPointer \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtemporaryfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractitemmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qidentityproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qitemselectionmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsortfilterproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringlistmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonarray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonvalue.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsondocument.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstracteventdispatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeventloop.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractnativeeventfilter.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbasictimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcoreapplication.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmath.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmetaobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimedata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectcleanuphandler.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedmemory.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsignalmapper.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsocketnotifier.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsystemsemaphore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtranslator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qwineventnotifier.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimedatabase.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimetype.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfactoryinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlibrary.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qplugin.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpluginloader.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/quuid.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstracttransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeventtransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfinalstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qhistorystate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsignaltransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstatemachine.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qexception.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuture.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfutureinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrunnable.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qresultstore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuturesynchronizer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuturewatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qreadwritelock.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsemaphore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthread.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthreadpool.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthreadstorage.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qwaitcondition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydataops.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydatapointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbitarray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbytearraymatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcollator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcommandlineoption.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcommandlineparser.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcryptographichash.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qelapsedtimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlinkedlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmessageauthenticationcode.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qqueue.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qregularexpression.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qscopedvaluerollback.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstack.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextboundaryfinder.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimeline.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimezone.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qxmlstream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtcoreversion.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qabstractnetworkcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkrequest.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QSharedDataPointer \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QString \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QUrl \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QVariant \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhttpmultipart.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QByteArray \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QIODevice \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QNetworkRequest \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QSslConfiguration \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtcpsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qabstractsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslerror.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcertificate.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qssl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QFlags \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkcookie.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QList \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QMetaType \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkcookiejar.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkdiskcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkreply.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QNetworkAccessManager \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkconfigmanager.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworksession.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhostaddress.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qauthenticator.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qdnslookup.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhostinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkproxy.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qlocalserver.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qlocalsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtcpserver.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qudpsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcertificateextension.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcipher.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslkey.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtnetworkversion.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QDebug \
		baiduapidictresult.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonDocument \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonArray \
		translate.h
	/home/stephen/Qt5.3.1/5.3/gcc/bin/moc $(DEFINES) -I/home/stephen/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I/home/stephen/project/openTranslate -I/home/stephen/Qt5.3.1/5.3/gcc/include -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtQuick -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtQml -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtWidgets -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtNetwork -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtGui -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtCore translate.h -o moc_translate.cpp

moc_baiduapidictresult.cpp: ../../Qt5.3.1/5.3/gcc/include/QtCore/QObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QStringList \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonDocument \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsondocument.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonvalue.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonArray \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonarray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QDebug \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		baiduapidictresult.h
	/home/stephen/Qt5.3.1/5.3/gcc/bin/moc $(DEFINES) -I/home/stephen/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I/home/stephen/project/openTranslate -I/home/stephen/Qt5.3.1/5.3/gcc/include -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtQuick -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtQml -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtWidgets -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtNetwork -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtGui -I/home/stephen/Qt5.3.1/5.3/gcc/include/QtCore baiduapidictresult.h -o moc_baiduapidictresult.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt5.3.1/5.3/gcc/include/QtWidgets/QApplication \
		../../Qt5.3.1/5.3/gcc/include/QtWidgets/qapplication.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcoreapplication.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeventloop.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		../../Qt5.3.1/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		../../Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qguiapplication.h \
		../../Qt5.3.1/5.3/gcc/include/QtGui/qinputmethod.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/QQmlEngine \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmlengine.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qjsengine.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qjsvalue.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qtqmlglobal.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmlerror.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmldebug.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/QQmlComponent \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmlcomponent.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqml.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmlprivate.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmlparserstatus.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmlpropertyvaluesource.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmllist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmetaobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtQml/QQmlContext \
		../../Qt5.3.1/5.3/gcc/include/QtQml/qqmlcontext.h \
		translate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QObject \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QtNetwork \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QtNetworkDepends \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QtCore \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QtCoreDepends \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qparallelanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpauseanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpropertyanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvariantanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeasingcurve.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsequentialanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextcodec.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qendian.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlibraryinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdatetime.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbuffer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdir.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfileinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdiriterator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfileselector.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QStringList \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfilesystemwatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlockfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qloggingcategory.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qprocess.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qresource.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsavefile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsettings.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstandardpaths.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtemporarydir.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QScopedPointer \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtemporaryfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractitemmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qidentityproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qitemselectionmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsortfilterproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringlistmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonarray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonvalue.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsondocument.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstracteventdispatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractnativeeventfilter.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbasictimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmath.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimedata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectcleanuphandler.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedmemory.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsignalmapper.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsocketnotifier.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsystemsemaphore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtranslator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qwineventnotifier.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimedatabase.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimetype.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfactoryinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlibrary.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qplugin.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpluginloader.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/quuid.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstracttransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeventtransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfinalstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qhistorystate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsignaltransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstatemachine.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qexception.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuture.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfutureinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrunnable.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qresultstore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuturesynchronizer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuturewatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qreadwritelock.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsemaphore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthread.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthreadpool.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthreadstorage.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qwaitcondition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydataops.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydatapointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbitarray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbytearraymatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcollator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcommandlineoption.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcommandlineparser.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcryptographichash.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qelapsedtimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlinkedlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmessageauthenticationcode.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qqueue.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qregularexpression.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qscopedvaluerollback.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstack.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextboundaryfinder.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimeline.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimezone.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qxmlstream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtcoreversion.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qabstractnetworkcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkrequest.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QSharedDataPointer \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QString \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QUrl \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QVariant \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhttpmultipart.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QByteArray \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QIODevice \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QNetworkRequest \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QSslConfiguration \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtcpsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qabstractsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslerror.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcertificate.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qssl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QFlags \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkcookie.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QList \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QMetaType \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkcookiejar.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkdiskcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkreply.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QNetworkAccessManager \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkconfigmanager.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworksession.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhostaddress.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qauthenticator.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qdnslookup.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhostinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkproxy.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qlocalserver.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qlocalsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtcpserver.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qudpsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcertificateextension.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcipher.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslkey.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtnetworkversion.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QDebug \
		baiduapidictresult.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonDocument \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonArray \
		global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

translate.o: translate.cpp translate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QtNetwork \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QtNetworkDepends \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QtCore \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QtCoreDepends \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qparallelanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpauseanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpropertyanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvariantanimation.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeasingcurve.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsequentialanimationgroup.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextcodec.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qendian.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlibraryinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdatetime.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbuffer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdir.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfileinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdiriterator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfileselector.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QStringList \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfilesystemwatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlockfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qloggingcategory.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qprocess.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qresource.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsavefile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsettings.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstandardpaths.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtemporarydir.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QScopedPointer \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtemporaryfile.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractitemmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qidentityproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qitemselectionmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsortfilterproxymodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringlistmodel.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonarray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonvalue.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsondocument.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstracteventdispatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeventloop.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractnativeeventfilter.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbasictimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcoreapplication.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmath.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmetaobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimedata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectcleanuphandler.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsharedmemory.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsignalmapper.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsocketnotifier.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsystemsemaphore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtranslator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qwineventnotifier.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimedatabase.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmimetype.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfactoryinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlibrary.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qplugin.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpluginloader.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/quuid.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstractstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qabstracttransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qeventtransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfinalstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qhistorystate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsignaltransition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstate.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstatemachine.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qexception.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuture.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfutureinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrunnable.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qresultstore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuturesynchronizer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfuturewatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qreadwritelock.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsemaphore.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthread.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthreadpool.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qthreadstorage.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qwaitcondition.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydataops.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydatapointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbitarray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbytearraymatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcollator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcommandlineoption.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcommandlineparser.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcryptographichash.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qelapsedtimer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlinkedlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmessageauthenticationcode.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qqueue.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qregularexpression.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qscopedvaluerollback.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstack.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextboundaryfinder.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimeline.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtimezone.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qxmlstream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtcoreversion.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qabstractnetworkcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkrequest.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QSharedDataPointer \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QString \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QUrl \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QVariant \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhttpmultipart.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QByteArray \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QIODevice \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QNetworkRequest \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QSslConfiguration \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtcpsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qabstractsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslerror.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcertificate.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qssl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QFlags \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkcookie.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QList \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QMetaType \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkcookiejar.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkdiskcache.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkreply.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/QNetworkAccessManager \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkconfigmanager.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworksession.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkinterface.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhostaddress.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qauthenticator.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qdnslookup.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qhostinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qnetworkproxy.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qlocalserver.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qlocalsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtcpserver.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qudpsocket.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcertificateextension.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslcipher.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qsslkey.h \
		../../Qt5.3.1/5.3/gcc/include/QtNetwork/qtnetworkversion.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QDebug \
		baiduapidictresult.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonDocument \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonArray \
		global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o translate.o translate.cpp

baiduapidictresult.o: baiduapidictresult.cpp baiduapidictresult.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QStringList \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonDocument \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsondocument.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonvalue.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonObject \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonobject.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QJsonArray \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qjsonarray.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/QDebug \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baiduapidictresult.o baiduapidictresult.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_translate.o: moc_translate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_translate.o moc_translate.cpp

moc_baiduapidictresult.o: moc_baiduapidictresult.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_baiduapidictresult.o moc_baiduapidictresult.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/openTranslate/bin || mkdir -p $(INSTALL_ROOT)/opt/openTranslate/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/openTranslate/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/openTranslate/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/openTranslate/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
